languageCode: en-us
baseURL: "//chanin.tech/"
title: Richards Britto
paginate: 10
theme: 
  - PaperMod
  - hugo-shortcode-gallery

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false


#googleAnalytics: UA-123-45

minify:
  disableXML: true
  minifyOutput: true

pygmentsUseClasses: false
pygmentsCodefences: true
pygmentsStyle: "fortnite"

markup:
  highlight:
    codeFences: true
    guessSyntax: false
    hl_Lines: ""
    lineNoStart: 1
    lineNos: false
    lineNumbersInTable: true
    noClasses: true
    tabWidth: 2

params:
  env: production # to enable google analytics, opengraph, twitter-cards and schema.
  title: RichardsBritto
  description: "Document my learning notes."
  keywords: [Blog, Portfolio, SLAM, Deep Learning, Computer Vision]
  author: Richards Britto
  # author: ["Me", "You"] # multiple authors
  #images: ["<link or path of image for opengraph, twitter-cards>"]
  DateFormat: "January 2, 2006"
  defaultTheme: light # auto, dark, light
  disableThemeToggle: false
  math: true
  ShowReadingTime: true
  ShowShareButtons: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: false
  ShowCodeCopyButtons: true
  disableSpecial1stPost: false
  disableScrollToTop: false
  comments: false
  hidemeta: false
  hideSummary: false
  showtoc: false
  tocopen: false

  label:
    text: "Richards' Workspace"
    icon: "images/camera.png"
    iconHeight: 35

  # profile-mode
  profileMode:
    enabled: true # needs to be explicitly set
    title: "Namaste Namaskaram Vanakkam 🙏"
    subtitle: "A curious earthling looking for optimal solutions under the specified 
    constraints and trying to function at different levels of abstraction.
     In this chronicle, I share my expedition of discovery and learning in
      the domains of computer vision, autonomous driving, and deep learning."
    imageUrl: "images/dp_5.png"
    imageWidth: 120
    imageHeight: 120
    imageTitle: "Ric"
    buttons:
      - name: Blogs
        url: blogs
      - name: Projects
        url: projects
      - name: Resume
        url: /docs/RESUME.pdf

  # home-info mode
  homeInfoParams:
    Title: "Welcome! \U0001F44B"
    Content: "This is the website of **Richards Britto.** and
    I create educational content on data science and bioinformatics.
    Some of you may know me as the **Data Professor**."

  socialIcons:
    #- name: youtube
    #  url: "http://youtube.com/dataprofessor"
    #- name: medium
    #  url: "https://medium.com/@data-professor"
    #- name: twitter
    #  url: "https://twitter.com/thedataprof"
    - name: linkedin
      url: "https://www.linkedin.com/in/ric1779/"
    - name: github
      url: "https://github.com/Ric1779"
    - name: instagram
      url: "https://www.instagram.com/crichardsbritto/"
    #- name: buymeacoffee
    #  url: "https://www.buymeacoffee.com/dataprofessor"

  analytics:
    google:
      SiteVerificationTag: "XYZabc"
    bing:
      SiteVerificationTag: "XYZabc"
    yandex:
      SiteVerificationTag: "XYZabc"

  cover:
    hidden: true # hide everywhere but not in structured data
    hiddenInList: true # hide on list pages and home
    hiddenInSingle: false # hide on single page


  editPost:
#    URL: "https://github.com/chanin-www/content"
#    Text: "Suggest Changes" # edit text
    URL: ""
    Text: "" # edit text
    appendFilePath: true # to append file path to Edit link

  # for search
  # https://fusejs.io/api/options.html
  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    keys: ["title", "permalink", "summary", "content"]
menu:
  main:
    #- identifier: about
    #  name: About
    #  url: /about/
    #  weight: 1
    - identifier: blog
      name: Blogs
      url: /blogs/
      weight: 1   
    - identifier: projects
      name: Projects
      url: /projects/
      weight: 2
    - identifier: 3D Modelling
      name: 3D Modelling
      url: /3D Modelling/
      weight: 3
    - identifier: Drawing
      name: Drawing
      url: /Drawing/
      weight: 4
    #- identifier: tags
    #  name: tags
    #  url: /tags/
    #  weight: 5