languageCode: en-us
baseURL: "//chanin.tech/"
title: Richards Britto
paginate: 10
theme: 
  - PaperMod
  - hugo-shortcode-gallery

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false

#googleAnalytics: UA-123-45

minify:
  disableXML: true
  minifyOutput: true

markup:
  highlight:
    codeFences: false
    lineNos: false
    noClasses: true
    style: monokai

params:
  env: production # to enable google analytics, opengraph, twitter-cards and schema.
  title: RichardsBritto
  description: "Document my learning notes."
  keywords: [Blog, Portfolio, SLAM, Deep Learning, Computer Vision]
  author: Richards Britto
  # author: ["Me", "You"] # multiple authors
  #images: ["<link or path of image for opengraph, twitter-cards>"]
  DateFormat: "January 2, 2006"
  defaultTheme: dark # auto, dark, light
  disableThemeToggle: false

  ShowReadingTime: true
  ShowShareButtons: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: false
  ShowCodeCopyButtons: true
  disableSpecial1stPost: false
  disableScrollToTop: false
  comments: false
  hidemeta: false
  hideSummary: false
  showtoc: false
  tocopen: false

  label:
    text: "Richards' Workspace"
    icon: "images/camera.png"
    iconHeight: 35

  # profile-mode
  profileMode:
    enabled: true # needs to be explicitly set
    title: "Welcome!"
    subtitle: "This is the website of Richards. Here I document my journey of learning and exploration in the 
    realms of computer vision, deep learning and mathematics. Through my blogs, I share my insights and 
    experiences as I delve into these fascinating subjects."
    imageUrl: "images/soldier-modified.png"
    imageWidth: 120
    imageHeight: 120
    imageTitle: "Ric"
    buttons:
      - name: Blogs
        url: blogs
      - name: Projects
        url: projects

  # home-info mode
  homeInfoParams:
    Title: "Welcome! \U0001F44B"
    Content: "This is the website of **Richards Britto.** and
    I create educational content on data science and bioinformatics.
    Some of you may know me as the **Data Professor**."

  socialIcons:
    #- name: youtube
    #  url: "http://youtube.com/dataprofessor"
    #- name: medium
    #  url: "https://medium.com/@data-professor"
    #- name: twitter
    #  url: "https://twitter.com/thedataprof"
    - name: linkedin
      url: "https://www.linkedin.com/in/chanin-nantasenamat/"
    - name: github
      url: "https://github.com/dataprofessor"
    #- name: buymeacoffee
    #  url: "https://www.buymeacoffee.com/dataprofessor"

  analytics:
    google:
      SiteVerificationTag: "XYZabc"
    bing:
      SiteVerificationTag: "XYZabc"
    yandex:
      SiteVerificationTag: "XYZabc"

  cover:
    hidden: true # hide everywhere but not in structured data
    hiddenInList: true # hide on list pages and home
    hiddenInSingle: false # hide on single page


  editPost:
#    URL: "https://github.com/chanin-www/content"
#    Text: "Suggest Changes" # edit text
    URL: ""
    Text: "" # edit text
    appendFilePath: true # to append file path to Edit link

  # for search
  # https://fusejs.io/api/options.html
  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    keys: ["title", "permalink", "summary", "content"]
menu:
  main:
    #- identifier: about
    #  name: About
    #  url: /about/
    #  weight: 1
    - identifier: blog
      name: Blogs
      url: /blogs/
      weight: 1   
    - identifier: projects
      name: Projects
      url: /projects/
      weight: 2
    - identifier: 3D Modelling
      name: 3D Modelling
      url: /3D Modelling/
      weight: 3
    - identifier: Drawing
      name: Drawing
      url: /Drawing/
      weight: 4
    - identifier: tags
      name: tags
      url: /tags/
      weight: 5
    # - name: Hugo
    #   params:
    #     rel: external
    #   pre: <i class="fa fa-heart"></i>
    #   url: https://gohugo.io/
    #   weight: 30

    #- identifier: example
    #  name: example.org
    #  url: https://example.org
    #  weight: 30
# Read: https://github.com/adityatelange/hugo-PaperMod/wiki/FAQs#using-hugos-syntax-highlighter-chroma
# pygmentsUseClasses: true
# markup:
#     highlight:
#         # anchorLineNos: true
#         codeFences: true
#         guessSyntax: true
#         lineNos: true
#         style: monokai